FROM golang:1.19.2-alpine AS build
RUN apk add --no-cache gcc libc-dev git

WORKDIR /go/src/app
COPY . .

RUN go mod download
RUN go build -o /bin/go-app ./cmd

FROM alpine:3.16.2

COPY --from=build /bin/go-app /usr/local/bin/go-app
ENTRYPOINT ["go-app"]
